#!/bin/sh

set -e

failed=0
for file in tests/*_test.sh; do
  rc=0
  echo "$file"
  mispipe "sh $file" "sed -e 's/ASSERT:/FAILED:/; s/^/  /'" || rc=$?
  if [ $rc -ne 0 ]; then
    failed=1
  fi
done

exit $failed
