language: ruby
source: ./spec/samples/rubySyntaxParts/repetition/mixConditionalRepetition.rb
output: ./spec/language/ruby/global_test/conditional_and_repetition/mixConditionalRepetition.xml
extract: uml
